nginx:
  build: ./config_nginx
  ports:
    # Ports: <HOST:CONTAINER>
    # Take care not to be using the following ports for any other service
    - 8085:80
  links:
    - php
  volumes_from:
    - app

php:
  build: ./config_php
  expose:
    - 9000
  links:
    - mysql 
  volumes_from:
    - app

app:
  # image: php:7.0-fpm
  image: php:7.1-fpm-alpine
  volumes:
    - ./myappname:/var/www/html/app
  command: "true"

mysql:
  image: mysql:5.7.20
  # image: mysql:latest
  volumes_from:
    - data
  environment:
    # user= root / password= secret
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: project
    # user= project / password = project
    MYSQL_USER: project
    MYSQL_PASSWORD: project

data:
  image: mysql:5.7.20
  # image: mysql:latest
  volumes:
    - /var/lib/mysql 
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.7
  # image: phpmyadmin/phpmyadmin
  ports: 
    - 8090:80
  links:
    - mysql 
  environment:
    PMA_HOST: mysql 
