version: '2'
services:
    nginx:
        build: ./config_nginx
        restart: always
        ports:
            # Ports: <HOST:CONTAINER>
            # Take care not to be using the following ports for any other service
            - 8085:80
        volumes: 
            #- ./default.conf:/etc/nginx/conf.d/default.conf
            - ./myappname:/var/www/html/app
        networks:
          - appnet

    php:
        build: ./config_php
        restart: always
        expose:
            - 9000

        volumes: 
          - ./myappname:/var/www/html/app
        networks:
          - appnet          

    mysql:
        image: mysql:5.7.20
        restart: always
        environment:
            # user= root / password= secret
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            # user= project / password = project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        networks:
          - appnet            

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        # image: phpmyadmin/phpmyadmin
        ports: 
          - 8090:80
        links:
          - mysql 
        environment:
          PMA_HOST: mysql 
        networks:
          - appnet          

networks:
  appnet:
    # Use a custom driver
   # driver: custom-driver-1
